### ISSUE TITLE
Comments for todo items

### ISSUE THREAD

**Issue by simondarke** [simondarke/todoboi__api#6]
Need a couple of bits

- [x] Table to keep em
- [x] Association with todo item
- [x] Endpoint for it all

**Comment by simondarke** [comment]
Done in be55c0666f57b92e90d65a47a45b2d9e17716e7d but I forgot to add it to the commit
